apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model
        image: ml-model:local
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-model-svc
  namespace: monitoring
spec:
  selector:
    app: ml-model
  ports:
  - port: 8000
    targetPort: 8000
